extends Node

## Auto-generated by Logic Bricks plugin
## Global variables shared across all scenes
## Do not edit between the markers

# === LOGIC BRICKS GLOBALS START ===
var score: int = 0
var new_global: String = "0"
var test_global: String = "0"
# === LOGIC BRICKS GLOBALS END ===
