extends Node

## Auto-generated by Logic Bricks plugin
## Global variables shared across all scenes
## Do not edit between the markers

# === LOGIC BRICKS GLOBALS START ===

# === LOGIC BRICKS GLOBALS END ===
